### ISSUE TITLE
Hey, does this work for other Nike domains as well? 

### ISSUE THREAD

**Issue by adityasanehi** [odiinthefirst/SNKRSRelaseMonitor#1]
What do I need to change, I could really make use of this.

**Comment by odiinthefirst** [comment]
I assume so, as long as elements have the same class names it should still work fine. all you would have to do is change the URL from GB to your country code.

Let me know how that goes!

**Comment by adityasanehi** [comment]
I tried it, it said I'm not allowed to access it. Dw, found a product feed API instead, works w that.

**Comment by adityasanehi** [comment]
Hey, not relevant but, would you have any idea what endpoint/API to use to scrape nike general releases?

**Comment by odiinthefirst** [comment]
Just saw this, I don't know of an API myself.
